/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppNoticesRouteImport } from './routes/_app/notices'
import { Route as AppBranchesRouteImport } from './routes/_app/branches'
import { Route as AppBoardOfDirectorsRouteImport } from './routes/_app/board-of-directors'
import { Route as AppBannersRouteImport } from './routes/_app/banners'
import { Route as AppAdminsRouteImport } from './routes/_app/admins'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNoticesRoute = AppNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AppRoute,
} as any)
const AppBranchesRoute = AppBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AppRoute,
} as any)
const AppBoardOfDirectorsRoute = AppBoardOfDirectorsRouteImport.update({
  id: '/board-of-directors',
  path: '/board-of-directors',
  getParentRoute: () => AppRoute,
} as any)
const AppBannersRoute = AppBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminsRoute = AppAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/admins': typeof AppAdminsRoute
  '/banners': typeof AppBannersRoute
  '/board-of-directors': typeof AppBoardOfDirectorsRoute
  '/branches': typeof AppBranchesRoute
  '/notices': typeof AppNoticesRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admins': typeof AppAdminsRoute
  '/banners': typeof AppBannersRoute
  '/board-of-directors': typeof AppBoardOfDirectorsRoute
  '/branches': typeof AppBranchesRoute
  '/notices': typeof AppNoticesRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admins': typeof AppAdminsRoute
  '/_app/banners': typeof AppBannersRoute
  '/_app/board-of-directors': typeof AppBoardOfDirectorsRoute
  '/_app/branches': typeof AppBranchesRoute
  '/_app/notices': typeof AppNoticesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admins'
    | '/banners'
    | '/board-of-directors'
    | '/branches'
    | '/notices'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admins'
    | '/banners'
    | '/board-of-directors'
    | '/branches'
    | '/notices'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/admins'
    | '/_app/banners'
    | '/_app/board-of-directors'
    | '/_app/branches'
    | '/_app/notices'
    | '/_app/settings'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notices': {
      id: '/_app/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof AppNoticesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/branches': {
      id: '/_app/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AppBranchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/board-of-directors': {
      id: '/_app/board-of-directors'
      path: '/board-of-directors'
      fullPath: '/board-of-directors'
      preLoaderRoute: typeof AppBoardOfDirectorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/banners': {
      id: '/_app/banners'
      path: '/banners'
      fullPath: '/banners'
      preLoaderRoute: typeof AppBannersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admins': {
      id: '/_app/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AppAdminsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminsRoute: typeof AppAdminsRoute
  AppBannersRoute: typeof AppBannersRoute
  AppBoardOfDirectorsRoute: typeof AppBoardOfDirectorsRoute
  AppBranchesRoute: typeof AppBranchesRoute
  AppNoticesRoute: typeof AppNoticesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminsRoute: AppAdminsRoute,
  AppBannersRoute: AppBannersRoute,
  AppBoardOfDirectorsRoute: AppBoardOfDirectorsRoute,
  AppBranchesRoute: AppBranchesRoute,
  AppNoticesRoute: AppNoticesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
